In [25]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/prathamd69/datasets/refs/heads/main/healthdataset.csv')

In [26]:
df['Health_Status'].unique()

array(['Healthy', 'Overweight', 'Obese', 'Underweight'], dtype=object)

In [27]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000
mean,48.817167,168.592533,74.070933,26.094300,2286.223833,2490.520333,123.773150,288.035317,93.698417,2.734917
std,18.141837,9.160213,12.417877,4.162643,469.541134,602.279679,61.999158,123.914738,43.953993,0.681486
min,18.000000,145.000000,40.000000,12.900000,1223.000000,1000.000000,17.400000,-23.600000,23.200000,1.500000
25%,33.000000,161.700000,65.500000,23.300000,1941.000000,2057.000000,78.800000,229.100000,65.900000,2.200000
50%,48.000000,168.200000,74.100000,26.000000,2232.500000,2433.000000,108.900000,297.150000,82.300000,2.600000
75%,65.000000,175.200000,82.700000,28.900000,2581.250000,2859.000000,155.100000,366.125000,105.100000,3.100000
max,80.000000,198.600000,116.600000,44.000000,4079.000000,5158.000000,457.500000,729.700000,341.700000,5.000000

In [28]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,P0001,50,Male,176.4,74.8,24.0,Very Active,2852,2625,183.0,16.9,202.8,3.3,Keto,Healthy
1,P0002,18,Female,167.6,75.5,26.9,Sedentary,1904,2044,90.1,306.5,50.8,1.9,Vegan,Overweight
2,P0003,68,Female,161.9,87.2,33.3,Lightly Active,2009,2540,222.7,281.3,58.2,2.4,High Protein,Obese
3,P0004,22,Female,169.3,66.9,23.3,Moderately Active,2318,2096,69.5,299.8,68.7,2.9,Balanced,Healthy
4,P0005,30,Male,179.1,75.3,23.5,Sedentary,2144,1937,32.9,285.6,73.7,2.2,Balanced,Healthy

In [29]:
df['Activity_Level'].unique()

array(['Very Active', 'Sedentary', 'Lightly Active', 'Moderately Active',
       'Athlete'], dtype=object)

In [30]:
df['daily_calorie_index'] = df['Daily_Calorie_Consumed'] - df['Daily_Calorie_Requirement']
df = df.drop(columns=['Daily_Calorie_Consumed', 'Daily_Calorie_Requirement'])

In [31]:
df = df.drop(columns=['Person_ID'])

In [ ]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index
0,50,Male,176.4,74.8,24.0,Very Active,183.0,16.9,202.8,3.3,Keto,Healthy,-227
1,18,Female,167.6,75.5,26.9,Sedentary,90.1,306.5,50.8,1.9,Vegan,Overweight,140
2,68,Female,161.9,87.2,33.3,Lightly Active,222.7,281.3,58.2,2.4,High Protein,Obese,531
3,22,Female,169.3,66.9,23.3,Moderately Active,69.5,299.8,68.7,2.9,Balanced,Healthy,-222
4,30,Male,179.1,75.3,23.5,Sedentary,32.9,285.6,73.7,2.2,Balanced,Healthy,-207
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,45,Female,161.1,79.1,30.5,Lightly Active,85.0,305.9,81.4,2.4,Balanced,Obese,257
5996,53,Female,157.7,63.7,25.6,Sedentary,177.0,179.7,47.1,1.8,High Protein,Overweight,296
5997,43,Female,154.0,81.8,34.5,Athlete,139.7,483.3,123.2,4.4,Mediterranean,Obese,761
5998,51,Female,162.8,77.8,29.4,Lightly Active,118.7,51.9,160.4,2.8,Keto,Overweight,132
5999,25,Male,171.5,75.9,25.8,Athlete,163.3,623.0,95.1,4.4,Vegan,Overweight,607

In [32]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [33]:
df['Gender'] = le.fit_transform(df['Gender'])

In [34]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index
0,50,1,176.4,74.8,24.0,Very Active,183.0,16.9,202.8,3.3,Keto,Healthy,-227
1,18,0,167.6,75.5,26.9,Sedentary,90.1,306.5,50.8,1.9,Vegan,Overweight,140
2,68,0,161.9,87.2,33.3,Lightly Active,222.7,281.3,58.2,2.4,High Protein,Obese,531
3,22,0,169.3,66.9,23.3,Moderately Active,69.5,299.8,68.7,2.9,Balanced,Healthy,-222
4,30,1,179.1,75.3,23.5,Sedentary,32.9,285.6,73.7,2.2,Balanced,Healthy,-207
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,161.1,79.1,30.5,Lightly Active,85.0,305.9,81.4,2.4,Balanced,Obese,257
5996,53,0,157.7,63.7,25.6,Sedentary,177.0,179.7,47.1,1.8,High Protein,Overweight,296
5997,43,0,154.0,81.8,34.5,Athlete,139.7,483.3,123.2,4.4,Mediterranean,Obese,761
5998,51,0,162.8,77.8,29.4,Lightly Active,118.7,51.9,160.4,2.8,Keto,Overweight,132
5999,25,1,171.5,75.9,25.8,Athlete,163.3,623.0,95.1,4.4,Vegan,Overweight,607

In [35]:
from sklearn.preprocessing import OrdinalEncoder
ordered_categories = [['Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Athlete']]

# Initialize the encoder with your specific hierarchy
encoder = OrdinalEncoder(categories=ordered_categories)
df['Activity_Encoded'] = encoder.fit_transform(df[['Activity_Level']])
df = df.drop(columns=['Activity_Level'])

In [36]:
df = df.drop(columns=['Height_cm','Weight_kg'])

In [13]:
df

,Age,Gender,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index,Activity_Encoded
0,50,1,24.0,183.0,16.9,202.8,3.3,Keto,Healthy,-227,3.0
1,18,0,26.9,90.1,306.5,50.8,1.9,Vegan,Overweight,140,0.0
2,68,0,33.3,222.7,281.3,58.2,2.4,High Protein,Obese,531,1.0
3,22,0,23.3,69.5,299.8,68.7,2.9,Balanced,Healthy,-222,2.0
4,30,1,23.5,32.9,285.6,73.7,2.2,Balanced,Healthy,-207,0.0
...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,30.5,85.0,305.9,81.4,2.4,Balanced,Obese,257,1.0
5996,53,0,25.6,177.0,179.7,47.1,1.8,High Protein,Overweight,296,0.0
5997,43,0,34.5,139.7,483.3,123.2,4.4,Mediterranean,Obese,761,4.0
5998,51,0,29.4,118.7,51.9,160.4,2.8,Keto,Overweight,132,1.0
5999,25,1,25.8,163.3,623.0,95.1,4.4,Vegan,Overweight,607,4.0

In [37]:
df['Health_Status'].unique()

array(['Healthy', 'Overweight', 'Obese', 'Underweight'], dtype=object)

In [38]:
rem = [[ 'Underweight','Healthy', 'Overweight', 'Obese']]

# Initialize the encoder with your specific hierarchy
encoder = OrdinalEncoder(categories=rem)
df['target'] = encoder.fit_transform(df[['Health_Status']])
df = df.drop(columns=['Health_Status'])

In [39]:
df

,Age,Gender,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,daily_calorie_index,Activity_Encoded,target
0,50,1,24.0,183.0,16.9,202.8,3.3,Keto,-227,3.0,1.0
1,18,0,26.9,90.1,306.5,50.8,1.9,Vegan,140,0.0,2.0
2,68,0,33.3,222.7,281.3,58.2,2.4,High Protein,531,1.0,3.0
3,22,0,23.3,69.5,299.8,68.7,2.9,Balanced,-222,2.0,1.0
4,30,1,23.5,32.9,285.6,73.7,2.2,Balanced,-207,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,30.5,85.0,305.9,81.4,2.4,Balanced,257,1.0,3.0
5996,53,0,25.6,177.0,179.7,47.1,1.8,High Protein,296,0.0,2.0
5997,43,0,34.5,139.7,483.3,123.2,4.4,Mediterranean,761,4.0,3.0
5998,51,0,29.4,118.7,51.9,160.4,2.8,Keto,132,1.0,2.0
5999,25,1,25.8,163.3,623.0,95.1,4.4,Vegan,607,4.0,2.0

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

onehotenc = OneHotEncoder(sparse_output=False)
onehotenc.fit(df[['Diet_Type']])
diet_encoded = onehotenc.transform(df[['Diet_Type']])

if hasattr(diet_encoded, "toarray"):
                diet_encoded_array = diet_encoded.toarray() # type:ignore
else:
                diet_encoded_array = diet_encoded

diet_encoded_df = pd.DataFrame(
diet_encoded_array, # type:ignore
columns=onehotenc.get_feature_names_out(['Diet_Type']),
index=df.index
            )   # type:ignore
df = pd.concat([df, diet_encoded_df], axis=1)

In [40]:
df = df.drop(columns=['Diet_Type'])

In [41]:
corr_matrix = df.corr()
corr_matrix.style.background_gradient(
    cmap="coolwarm", vmin=-1, vmax=1
).format(precision=2)

In [42]:
df = df.drop(columns=['Gender', 'Water_Intake_Liters'])

In [43]:
df

,Age,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,daily_calorie_index,Activity_Encoded,target
0,50,24.0,183.0,16.9,202.8,-227,3.0,1.0
1,18,26.9,90.1,306.5,50.8,140,0.0,2.0
2,68,33.3,222.7,281.3,58.2,531,1.0,3.0
3,22,23.3,69.5,299.8,68.7,-222,2.0,1.0
4,30,23.5,32.9,285.6,73.7,-207,0.0,1.0
...,...,...,...,...,...,...,...,...
5995,45,30.5,85.0,305.9,81.4,257,1.0,3.0
5996,53,25.6,177.0,179.7,47.1,296,0.0,2.0
5997,43,34.5,139.7,483.3,123.2,761,4.0,3.0
5998,51,29.4,118.7,51.9,160.4,132,1.0,2.0
5999,25,25.8,163.3,623.0,95.1,607,4.0,2.0

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_data,test_data = train_test_split(df, test_size=0.2, random_state=24)

In [45]:
cols_to_exclude = ['target', 'Activity_Encoded', 'Gender']

exclude_train = [col for col in cols_to_exclude if col in train_data.columns]
exclude_test = [col for col in cols_to_exclude if col in test_data.columns]

train_features_to_scale = train_data.drop(columns=exclude_train)
test_features_to_scale = test_data.drop(columns=exclude_test)
train_scaled_feats = pd.DataFrame(
    scaler.fit_transform(train_features_to_scale),
    columns=train_features_to_scale.columns,
    index=train_data.index
)

test_scaled_feats = pd.DataFrame(
    scaler.transform(test_features_to_scale),
    columns=test_features_to_scale.columns,
    index=test_data.index
)

train_final = pd.concat(
    [train_scaled_feats, train_data[exclude_train]],
    axis=1
)

test_final = pd.concat(
    [test_scaled_feats, test_data[exclude_test]],
    axis=1
)

In [46]:
train_final

,Age,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,daily_calorie_index,target,Activity_Encoded
89,-0.993693,-1.779577,0.712772,-0.619888,-0.595241,-1.424253,1.0,1.0
345,-0.993693,-0.050166,-0.203764,0.664622,-0.811736,0.621606,2.0,1.0
4715,1.493792,0.550324,-0.814787,0.142179,-0.703489,-0.161753,2.0,0.0
2577,0.996295,-1.635460,-0.679535,-0.698132,-0.708095,-1.420451,1.0,2.0
2424,-0.772583,-0.434480,-0.654075,1.011831,0.056548,-1.724668,1.0,3.0
...,...,...,...,...,...,...,...,...
2193,0.609353,-1.010950,-0.988229,-0.490296,-0.512328,-1.256934,1.0,2.0
3473,1.604347,-0.002127,-0.996185,-0.692427,-0.786402,-0.355691,2.0,0.0
343,-1.435912,-0.122225,0.300649,1.376156,-0.247467,0.473300,2.0,2.0
899,1.327960,1.270912,2.165544,-0.526158,-0.021759,1.473413,3.0,0.0
4514,-0.219808,-0.770754,-1.265099,-0.181394,-1.053566,-1.443267,1.0,1.0

In [47]:
target_col = "target"

X_train = train_final.drop(columns=[target_col])
y_train = train_final[target_col]

X_test = test_final.drop(columns=[target_col], errors="ignore")

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Features and target
X = train_final.drop(columns=['target','BMI'])
y = train_final['target']

# Split
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# Model
lr = LogisticRegression(
    max_iter=300,
    random_state=42
)

# Train
lr.fit(X_train, y_train)

# Predict
y_pred = lr.predict(X_val)

# Metrics
print("Accuracy :", accuracy_score(y_val, y_pred))
print("Precision:", precision_score(y_val, y_pred, average='weighted'))
print("Recall   :", recall_score(y_val, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_val, y_pred, average='weighted'))

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))

Accuracy : 0.8208333333333333
Precision: 0.8288555082241998
Recall   : 0.8208333333333333
F1 Score : 0.818768687548512

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.90      0.95        42
         1.0       0.87      0.88      0.88       541
         2.0       0.75      0.86      0.80       596
         3.0       0.88      0.61      0.72       261

    accuracy                           0.82      1440
   macro avg       0.88      0.81      0.84      1440
weighted avg       0.83      0.82      0.82      1440


Confusion Matrix:
[[ 38   4   0   0]
 [  0 474  67   0]
 [  0  64 511  21]
 [  0   0 102 159]]

In [63]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Split features and target
X_test = test_final.drop(columns=['target'])
y_test = test_final['target']

# Predict
y_test_pred = lr.predict(X_test)

# Metrics
print("Accuracy :", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_test_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_test_pred, average='weighted'))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

Accuracy : 0.9891666666666666
Precision: 0.9892143385070213
Recall   : 0.9891666666666666
F1 Score : 0.989124492758879

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.91      0.95        34
         1.0       0.98      0.99      0.99       447
         2.0       0.99      0.99      0.99       513
         3.0       1.00      0.99      0.99       206

    accuracy                           0.99      1200
   macro avg       0.99      0.97      0.98      1200
weighted avg       0.99      0.99      0.99      1200


Confusion Matrix:
[[ 31   3   0   0]
 [  0 444   3   0]
 [  0   4 508   1]
 [  0   0   2 204]]

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Train
dt = DecisionTreeClassifier(
    random_state=42,
    max_depth=2
)

dt.fit(X_train, y_train)

# Predict
y_pred = dt.predict(X_val)

# Metrics
print("Accuracy :", accuracy_score(y_val, y_pred))
print("Precision:", precision_score(y_val, y_pred, average='weighted'))
print("Recall   :", recall_score(y_val, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_val, y_pred, average='weighted'))

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        42
         1.0       1.00      1.00      1.00       541
         2.0       1.00      1.00      1.00       596
         3.0       1.00      1.00      1.00       261

    accuracy                           1.00      1440
   macro avg       1.00      1.00      1.00      1440
weighted avg       1.00      1.00      1.00      1440


Confusion Matrix:
[[ 42   0   0   0]
 [  0 541   0   0]
 [  0   0 596   0]
 [  0   0   0 261]]

In [74]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Split features and target
X_test = test_final.drop(columns=['target','BMI'])
y_test = test_final['target']

# Predict
y_test_pred = dt.predict(X_test)

# Metrics
print("Accuracy :", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_test_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_test_pred, average='weighted'))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [68]:
corr = train_final.corr(numeric_only=True)

print(corr['target'].sort_values(ascending=False))

target                   1.000000
BMI                      0.917570
daily_calorie_index      0.834147
Carbohydrate_Intake_g    0.261777
Fat_Intake_g             0.249325
Protein_Intake_g         0.213160
Age                      0.108275
Activity_Encoded        -0.213251
Name: target, dtype: float64

In [69]:
X = train_final.drop(columns=['target'])
y = train_final['target']

print('target' in X.columns)

False

In [70]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt.feature_importances_
})

print(
    importance.sort_values(
        'Importance',
        ascending=False
    ).head(20)
)

                 Feature  Importance
1                    BMI         1.0
0                    Age         0.0
2       Protein_Intake_g         0.0
3  Carbohydrate_Intake_g         0.0
4           Fat_Intake_g         0.0
5    daily_calorie_index         0.0
6       Activity_Encoded         0.0

In [71]:
print("Tree Depth:", dt.get_depth())
print("Number of Leaves:", dt.get_n_leaves())

Tree Depth: 2
Number of Leaves: 4

In [73]:
train_final.groupby('target')['BMI'].agg(
    ['min', 'max', 'mean']
)

             min       max      mean
target
0.0    -3.172714 -1.851636 -2.192510
1.0    -1.827617 -0.290362 -0.855542
2.0    -0.266342  0.910618  0.287039
3.0     0.934638  4.297382  1.471821